# Generated by Django 4.2.3 on 2023-07-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/articles', verbose_name='Foto')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Batafsil')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='ExamLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=255, verbose_name='Imtixon tili')),
            ],
            options={
                'verbose_name': 'Imtixon tili',
                'verbose_name_plural': 'Imtixon tillari',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=255, verbose_name="Ta'lim yo‘nalishi")),
                ('description', models.TextField(verbose_name='Batafsil ta‘lim yo‘nalishi haqida')),
                ('image', models.ImageField(upload_to='photos/directions_study', verbose_name='Ta‘lim yo‘nalishi foto')),
            ],
            options={
                'verbose_name': 'Yo‘nalish',
                'verbose_name_plural': 'Yo‘nalishlar',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255, verbose_name='Jins')),
            ],
            options={
                'verbose_name': 'Jins',
                'verbose_name_plural': 'Jinslar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Yangiliklar nomi')),
                ('min_to_read', models.IntegerField(verbose_name='O‘qishga ketadigan vaqt')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Yangilik qo‘shilgan sana')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Yangilik yangilangan sana')),
                ('status', models.BooleanField(default=True, verbose_name='Yangilik statusi')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=255, verbose_name='Yangiliklar kategoriyasi')),
            ],
            options={
                'verbose_name': 'Yangiliklar kategoriyasi',
                'verbose_name_plural': 'Yangiliklar kategoriyalari',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, verbose_name='Viloyat')),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
            },
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Ta‘lim shakli')),
            ],
            options={
                'verbose_name': "Ta'lim shakli",
                'verbose_name_plural': "Ta'lim shakllari",
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/news')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='university.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': 'Yangilik rasmi',
                'verbose_name_plural': 'Yangilik rasmlari',
            },
        ),
        migrations.CreateModel(
            name='NewsDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Yangilik batafsil')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='university.news', verbose_name='Yangilik')),
            ],
            options={
                'verbose_name': "Yangilik batafsil ma'lumoti",
                'verbose_name_plural': "Yangilik batafsil ma'lumotlari",
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.newscategory', verbose_name='Yangilik kategoriyasi'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=255, verbose_name='Familiya')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sanangiz")),
                ('district', models.CharField(max_length=255, verbose_name='Tuman')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('extra_phone_number', models.CharField(max_length=255, verbose_name='Telefon raqam')),
                ('passport_photo', models.ImageField(upload_to='photos/passports', verbose_name='Passport rangli nusxasi')),
                ('passport_series', models.CharField(max_length=2, verbose_name='Passport Seriya')),
                ('passport_numbers', models.IntegerField(verbose_name='Passport raqami')),
                ('diploma_photo', models.ImageField(upload_to='photos/diplomas', verbose_name='Diplom rangli nusxasi')),
                ('application_data', models.DateTimeField(auto_now=True, verbose_name='Dokument topshirilgan sana')),
                ('exam_lang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.examlang', verbose_name='Imtixon tili')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.faculty', verbose_name="Ta'lim yo‘nalishi")),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.gender', verbose_name='Jins')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.region', verbose_name='Viloyat')),
                ('study_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.studytype', verbose_name='Ta‘lim shakli')),
            ],
            options={
                'verbose_name': 'Ariza, Xujjat',
                'verbose_name_plural': 'Arizalar, Xujjatlar',
            },
        ),
    ]
