# Generated by Django 4.2.3 on 2023-07-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_sliderphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Batafsil ta‘lim yo‘nalishi haqida'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(null=True, unique=True, upload_to='photos/directions_study', verbose_name='Ta‘lim yo‘nalishi foto'),
        ),
    ]
